development:
  dialect: "mysql"
  database: "admin"
  host: {{ env "DB_HOST" }}
  port: "3306"
  user: {{ env "DB_USER" }}
  password: {{ env "DB_PASSWORD" }}

development_useraccounts:
  dialect: "mysql"
  database: "user_accounts"
  host: {{ env "DB_HOST" }}
  port: "3306"
  user: {{ env "DB_USER" }}
  password: {{ env "DB_PASSWORD" }}

development_userdata:
  dialect: "mysql"
  database: "user_data"
  host: {{ env "DB_HOST" }}
  port: "3306"
  user: {{ env "DB_USER" }}
  password: {{ env "DB_PASSWORD" }}

development_dailybonus:
  dialect: "mysql"
  database: "daily_bonus"
  host: {{ env "DB_HOST" }}
  port: "3306"
  user: {{ env "DB_USER" }}
  password: {{ env "DB_PASSWORD" }}

development_bot:
  dialect: "mysql"
  database: "bot"
  host: {{ env "DB_HOST" }}
  port: "3306"
  user: {{ env "DB_USER" }}
  password: {{ env "DB_PASSWORD" }}
